version: '3'
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
 
  api:
    build: ./api
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - ./api:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password4Mongo
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Password4Mongo
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongodb_data: